#!/bin/sh

exit 1

cp /root/OS/Programs/xorg/RunScript /usr/dockerscripts/xorg &&
chmod +x /usr/dockerscripts/xorg &&
mkdir -p /usr/dockerfiles/xorg &&
cp /root/OS/Programs/xorg/Dockerfile /usr/dockerfiles/xorg/Dockerfile &&
docker build -t xorg /usr/dockerfiles/xorg
