#!/bin/sh

cp /root/OS/Programs/android-studio/Runscript /usr/dockerscripts/android-studio &&
chmod +x /usr/dockerscripts/android-studio &&
mkdir -p /usr/dockerfiles/android-studio &&
cp /root/OS/Programs/android-studio/Dockerfile /usr/dockerfiles/android-studio/Dockerfile &&

cp -p /root/OS/Programs/android-studio/android-studio-ide-143.2915827-linux.zip /usr/dockerfiles/android-studio &&
cp -p /root/OS/Programs/android-studio/android-sdk_r24.4.1-linux.tgz /usr/dockerfiles/android-studio &&

docker build -t android-studio /usr/dockerfiles/android-studio
