#!/bin/sh

xterm &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
bspc monitor -g 1920x1040+0+40 &

bspc config border_width 5 &
bspc config window_gap 10 &

docker start docker-desktop
/root/OS/ConfigFiles/bspwm-pipes.sh &
/root/OS/ConfigFiles/host-info.sh &
